---
- name: Packer Ansible Provisioning for Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Chocolatey
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      args:
        executable: powershell.exe

    - name: Install Notepad++
      win_chocolatey:
        name: notepadplusplus
        state: present

    - name: Set Windows Welcome Message
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: legalnoticecaption
        data: "Welcome"
        type: string

    - name: Set Windows Welcome Message Text
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: legalnoticetext
        data: "This Windows AMI was created with Packer and Ansible."
        type: string
